=== carlossamuel/berlioz/resource/library/services-1.0.dtd
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->
<!--                                                                        -->
<!-- Title:         Berlioz DTD for Web Services                            -->
<!-- System:        Berlioz                                                 -->
<!-- Status:        Draft                                                   -->
<!-- Description:   A schema for the defining the URL patterns and          -->
<!--                associated content generators.                          -->
<!-- Version:       1.0                                                     -->
<!-- LastModified:  20 May 2010                                             -->
<!-- Author(s):     Christophe Lauret                                       -->
<!--                                                                        -->
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->

<!-- A URI Pattern as defined in the URI Template specifications            -->
<!ENTITY  % URI_PATTERN      "CDATA"                                          >

<!-- The HTTP method for the associated service                             -->
<!ENTITY  % HTTP_METHOD      "(get | put | delete | post )"                   >

<!-- The HTTP method for the associated service                             -->
<!ENTITY  % PARAMETER_SOURCE "(string | query-string | uri-variable )"        >

<!--
  Top level element.
-->
<!ELEMENT service-config                                        ( services* ) >
<!ATTLIST service-config     version            CDATA            #FIXED "1.0" >

<!--
  A container for generators from the same area.
-->
<!ELEMENT services                                               ( service* ) >
<!ATTLIST services           group              ID                  #REQUIRED >

<!--
  A content generator.
  
  @param id     A unique identifier for this service.
  @param method The HTTP method this service accepts.
-->
<!ELEMENT service                                        ( url+, generator* ) >
<!ATTLIST service            id                 ID                  #REQUIRED
                             method             %HTTP_METHOD;       #REQUIRED >

<!--
  The url pattern matching this service.

  @attribute pattern The URI Pattern for this URL.
-->
<!ELEMENT url                                                           EMPTY >
<!ATTLIST url                pattern            %URI_PATTERN;       #REQUIRED >

<!--
  The content generator class
-->
<!ELEMENT generator                                            ( parameter* ) >
<!ATTLIST generator         class               CDATA               #REQUIRED
                            target              NMTOKEN              #IMPLIED >

<!--
  A parameter to pass to the content generator
-->
<!ELEMENT parameter                                                    EMPTY >
<!ATTLIST parameter         name               CDATA               #REQUIRED 
                            value              CDATA               #REQUIRED
                            source             %PARAMETER_SOURCE;  #REQUIRED
                            default            CDATA                #IMPLIED >

=== carlossamuel/berlioz/test/data/org/weborganic/berlioz/content/ContentManager/S0/config/services.xml
<?xml version="1.0"?>
<!DOCTYPE service-config PUBLIC "-//Berlioz//DTD::Services 1.0//EN"
                                "../../../Core/resource/library/services-1.0.dtd" >
<!--
    A test services configuration file.

    @author  Christophe Lauret (Weborganic)
    @version 26 November 2009
-->
<service-config version="1.0">

  <services group="test">

    <service id="P01" method="get">
      <url pattern="/home"/>
      <generator class="org.weborganic.berlioz.content.NoContent">home</generator>
    </service>

    <service id="P02" method="get">
      <url pattern="/custom"/>
      <generator class="org.weborganic.berlioz.content.ContentManagerTest$Custom">custom</generator>
    </service>

    <service id="P03" method="get">
      <url pattern="/user/{userid}"/>
      <generator class="org.weborganic.berlioz.content.NoContent">user</generator>
    </service>

  </services>

</service-config>
