=== carlossamuel/berlioz/resource/library/web-access-1.0.dtd
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->
<!--                                                                -->
<!-- Title:         Berlioz DTD for Web Access                      -->
<!-- System:        Berlioz                                         -->
<!-- Status:        Deprecated                                      -->
<!-- Description:   A schema for the defining the URL patterns and  -->
<!--                associated content generators.                  -->
<!-- Version:       1.0                                             -->
<!-- LastModified:  9 October 2009                                  -->
<!-- Author(s):     Christophe Lauret                               -->
<!--                                                                -->
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->

<!--
  Top level element.
-->
<!ELEMENT web-access                                  ( generators* ) >

<!--
  A container for generators from the same area
-->
<!ELEMENT generators                                   ( generator* ) >
<!ATTLIST generators     area                     ID        #REQUIRED >

<!--
  A content generator.
-->
<!ELEMENT generator         ( path-info, redirect?, service, class? ) >
<!ATTLIST generator      id                       ID        #REQUIRED >

<!--
  The path info to follow
  
  The directory home attribute indicates that this page should be used
  as the default directory home.
-->
<!ELEMENT path-info                                       ( #PCDATA ) >
<!ATTLIST path-info      home          (true | false)        #IMPLIED >

<!--
  The redirect object associated to this content generator
-->
<!ELEMENT redirect                            (path-info, parameter*) >

<!--
  The parameter for any redirect
-->
<!ELEMENT parameter                                             EMPTY >
<!ATTLIST parameter      name                NMTOKEN        #REQUIRED >

<!--
  The content generator class
-->
<!ELEMENT class                                           ( #PCDATA ) >

<!--
  The content generator class
-->
<!ELEMENT service                                         ( #PCDATA ) >

=== carlossamuel/berlioz/test/data/org/weborganic/berlioz/content/ContentManager/A0/config/access.xml
<?xml version="1.0"?>
<!DOCTYPE web-access PUBLIC "-//Berlioz//DTD::Web Access 1.0//EN"
                            "../../../Core/resource/library/web-access-1.0.dtd">
<!--
    A test web access configuration file.

    @author  Christophe Lauret (Weborganic)
    @version 26 November 2009
-->
<web-access>

  <generators area="test">

    <generator id="P01">
      <path-info home="true">/home</path-info>
      <service>home</service>
    </generator>

    <generator id="P02">
      <path-info>/custom</path-info>
      <service>custom-service</service>
      <class>org.weborganic.berlioz.content.ContentManagerTest$Custom</class>
    </generator>

  </generators>

</web-access>
